import { createCatalog } from '../src/openapi.js';

export async function generateOpenApiDocs(content: string, apiUrl = 'https://api.tembo.io'): Promise<string> {
  const catalog = await createCatalog(content, apiUrl);
  const rows = [...catalog.entries]
    .sort((left, right) => left.path.localeCompare(right.path) || left.method.localeCompare(right.method))
    .map(({ method, path, tool }) => `| ${method} | \`${escapeCell(path)}\` | \`${escapeCell(tool.name)}\` | ${escapeCell(tool.description ?? '')} |`);

  return [
    '# Tembo MCP API Reference',
    '',
    '<!-- Generated by npm run update:openapi. Do not edit manually. -->',
    '',
    `This reference contains all ${rows.length} public API operations available through Tembo MCP. It is generated from the same versioned OpenAPI schema as the MCP tool catalog.`,
    '',
    'In compact mode, use `search_tools` and `get_tool_schema` to discover these operations, then call them with `call_read_tool` or `call_write_tool`.',
    '',
    '| Method | Path | MCP operation | Description |',
    '| --- | --- | --- | --- |',
    ...rows,
    '',
  ].join('\n');
}

function escapeCell(value: string): string {
  return value.replaceAll('|', '\\|').replaceAll('\n', ' ').trim();
}
